package:
  name: picklable-itertools 
  version: 0.1.1

source:
  git_url: https://github.com/mila-udem/picklable-itertools.git 
  git_tag: v0.1.1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

about:
  home: https://github.com/mila-udem/picklable-itertools
  license: MIT

