package:
  name: fuel
  version: 0.1.1

source:
  git_url: https://github.com/mila-udem/fuel.git 
  git_tag: v0.1.1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - six
    - picklable-itertools
    - pyyaml
    - h5py
    - pytables
    - progressbar2
    - pyzmq
    - scipy
    - pillow
    - requests

  run:
    - python
    - numpy
    - six
    - picklable-itertools
    - pyyaml
    - h5py
    - pytables
    - progressbar2
    - pyzmq
    - scipy
    - pillow
    - requests

about:
  home: https://fuel.readthedocs.org/en/latest/
  license: MIT

